environment: post-test
domainName:
  http: api.freeeasycrypto.com
  grpc: gapi.freeeasycrypto.com
apiService: crypto-api-service
appName: crypto-app-api
httpPort: 80
service:
  port: 80
ingress:
  enabled: true
  ingressClassName: nginx
gatewayClass: nginx
gateway:
  enabled: true
  nlbTarget: "k8s-myapp-cryptoap-5a72f400e1-fbe6dc3fa5bd9ce8.elb.us-east-1.amazonaws.com"
  publicSubnetIds: []
replicas: 2
image: 533267178572.dkr.ecr.us-east-1.amazonaws.com/crypto-ecr-repo:ebbdc29ad64062b8e2c6dd9ef26d7b48d75718bc
server: https://acme-v02.api.letsencrypt.org/directory
email: huzaifagill411@gmail.com
tlsSecretName:
  http: crypto-app-api-tls
  grpc: crypto-app-gapi-tls
ingressClass: nginx
hostedZoneId: Z01601922DP7HAM1NYV8Z
livenessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
readinessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 30
  periodSeconds: 5
