environment: post-test
domainName:
  http: api.freeeasycrypto.com
  grpc: gapi.freeeasycrypto.com
namespace: kube-system
apiService: crypto-api-service
appName: crypto-app-api
httpPort: 80
service:
  port: 80
ingress:
  enabled: true
  ingressClassName: nginx
gatewayClass: nginx-fabric
gateway:
  enabled: true
replicas: 2
image: 533267178572.dkr.ecr.us-east-1.amazonaws.com/crypto-ecr-repo:3d2709d69dc90f202deaab075775be6048cb5493
server: https://acme-v02.api.letsencrypt.org/directory
email: huzaifagill411@gmail.com
tlsSecretName:
  http: crypto-app-api-tls-secret
  grpc: crypto-app-gapi-tls-secret
ingressClass: nginx
hostedZoneId: Z01601922DP7HAM1NYV8Z
livenessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
readinessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 30
  periodSeconds: 5
