environment: post-test
domainName:
  http: api.freeeasycrypto.com
  grpc: gapi.freeeasycrypto.com
apiService: crypto-api-service
appName: crypto-app-api
httpPort: 80
service:
  port: 80
ingress:
  enabled: true
  ingressClassName: nginx
gatewayClass: nginx
gateway:
  enabled: true
  publicSubnetIds:
    - subnet-02787dacd96e67017
    - subnet-03f8f633d7e8ebde7
  nlbTarget: ""
replicas: 2
image: 533267178572.dkr.ecr.us-east-1.amazonaws.com/crypto-ecr-repo:f87eb121c5901a25790216fdd88a68cfa879d6d5
server: https://acme-v02.api.letsencrypt.org/directory
email: huzaifagill411@gmail.com
tlsSecretName:
  http: crypto-app-api-tls
  grpc: crypto-app-gapi-tls
ingressClass: nginx
hostedZoneId: Z01601922DP7HAM1NYV8Z
livenessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
readinessProbe:
  path: /healthz
  port: 8081
  initialDelaySeconds: 30
  periodSeconds: 5
