{{- if and .Values.gateway.enabled (eq .Values.environment "post-test") }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Values.appName }}-grpc-route
spec:
  parentRefs:
    - name: {{ .Values.appName }}-gateway
  hostnames:
    - {{ .Values.domainName.grpc }}
  rules:
    - matches: []                 
      backendRefs:
        - name: {{ .Values.apiService }}
          port: 90
{{- end }}