apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiService }}
  namespace: {{ .Values.namespace | default "my-app" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-02ba68c30aa99471a,subnet-0741a0ccc76183426
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
    - protocol: TCP
      port: 90
      targetPort: grpc-server
      name: grpc-service
  type: LoadBalancer