name: Checkov (Helm & Kubernetes)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          output_format: cli,sarif
          output_file_path: console,checkov-results.sarif
          soft_fail: false
